### ISSUE TITLE
Flaky E2E-Tests fixen

### ISSUE THREAD

**Issue by RandomTannenbaum** [puzzle/okr#1236]
Einige E2E-Tests sind flaky, was dazu führt das man die Pipeline babysitten muss. Sie schlagen in der Pipeline fehl, sind dann aber bei erneutem Ausführen OK.

### `duplicate-objective.cy.ts`
Der Test `Should not duplicate objective when cancel button is clicked` recht regelmässig  zu failen. 

```
CypressError: Timed out retrying after 4050ms: `cy.click()` failed because the center of this element is hidden from view:

`<button _ngcontent-ng-c1750590055="" mat-menu-item="" class="mat-mdc-menu-item mat-mdc-focus-indicator objective-menu-option ng-tns-c1923052698-14 ng-star-inserted" data-testid="objective-menu" role="menuitem" tabindex="0" aria-disabled="false" style="">...</button>`
``` 
Ein Beispiel kann man [hier](https://github.com/puzzle/okr/actions/runs/12388067390/job/34578552531) finden.

### `tab.cy.ts`
Der E2E Test namens `Should tab keyresult detail view` der sich im file `tab.cy.ts` befindet scheint flaky zu sein. Es ist schon mehrmals vorgekommen, dass er auf der Pipeline plötzlich failed. Das soll behoben werden.

Eine erste Vermutung die ich habe ist, dass wir irgendwo vielleicht einen unsafe call haben, also zum Beispiel ein `.find()` an ein `.scrollIntoView()` chainen. Vielleicht müssen wir auch die Strategie ändern, die wir brauchen, um zu wissen ob das sidepanel offen ist.

### `teammanagement.cy.ts`
Sehr selten schlägt der Test `should preserve team filter `  fehl, das Fixen dieses Tests halt also kleinere Prio.

```
AssertionError: Timed out retrying after 4000ms: Expected to find content: 'LoremIpsum' within the selector: 'h1:visible' but never did.
      at FilterHelper.optionShouldBeSelected (webpack://frontend/./cypress/support/helper/dom-helper/filterHelper.ts:6:0)
      at checkTeamsSelected (webpack://frontend/./cypress/e2e/teammanagement.cy.ts:28:24)
      at Context.eval (webpack://frontend/./cypress/e2e/teammanagement.cy.ts:20:0)
```

Ein Beispiel kann man [hier](https://github.com/puzzle/okr/actions/runs/12388062769/job/34578634627) finden.

### `overview.cy.ts`
Ebenfalls eher selten schlägt der `Check order of teams`-Test fehlt. Hat also ebenfalls eine niedrigere Prio.

```
AssertionError: Timed out retrying after 4000ms: Expected to find element: `.team-title:contains("we are cube.³")`, but never found it.
      at Context.eval (webpack://frontend/./cypress/e2e/overview.cy.ts:13:0)
``` 

Ein Beispiel kan man [hier](https://github.com/puzzle/okr/actions/runs/12415959927/job/34663498671) finden.

### `objective-crud.cy.ts`
Ebenfalls eher selten schlägt der `should not be able to delete a completed objective`-Test fehl.

```
CypressError: Timed out retrying after 4050ms: `cy.click()` failed because the center of this element is hidden from view:

`<button _ngcontent-ng-c1750590055="" mat-menu-item="" class="mat-mdc-menu-item mat-focus-indicator objective-menu-option ng-star-inserted" data-testid="objective-menu" role="menuitem" tabindex="0" aria-disabled="false">...</button>`
``` 

Ein Beispiel kan man [hier](https://github.com/puzzle/okr/actions/runs/12762607847/job/35571394253#logs) finden.

### Anforderungen
- Die E2E-Tests funktionieren wieder zuverlässig(er)

### Akzeptanzkriterien
- [ ] Die Tests läuft sowohl lokal als auch auf der pipeline nicht mehr flaky.
- [ ] Die Tests läuft sowohl headless als auch nicht ohne flaky zu sein.
- [ ] Die Tests wurde nach dem Fix  >20 Mal hintereinander in der Pipeline ausgeführt, ohne das sie ein einziges Mal fehlgeschlagen sind

**Comment by Miguel7373** [comment]
### Stand 14.1.2025

Ich habe den duplicate-objective.cy.ts Folder fokussiert, da mir dort mehrere Tests schon mal durchgeflogen sind und habe diese meines Wissens auch gefixt und genug oft durch die Pipe laufen lassen.

**Comment by RandomTannenbaum** [comment]
**Stand 15.01.2025**
Da ich das flaky behavior, sowohl lokal als auch auf der pipeline, nicht erreichen konnte haben wir uns dazu entschieden, keine weitere Zeit in dieses Ticket zu investieren.
